version: '3'
services:
  taurus-data-store-ms:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongo
    networks:
      - taurus-network
  mongo:
    image: mongo:4.2.0-bionic
    ports:
      - "27017:27017"
    networks:
      - taurus-network

networks:
  taurus-network:
    external: true
